name: update profile

# Controls when the action will run. This action runs every 6 hours.

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  schedule:
    - cron: '*/30 * * * *'

# # This command allows us to run the Action automatically from the Actions tab.
#   workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Pull latest main
        run: git pull origin main --rebase
      - name: bash update.sh
        run:  bash ./scripts/update.sh

      # - name: Push new files to the output branch
      #   uses: crazy-max/ghaction-github-pages@v3.1.0
      #   with:
      #     # the output branch we mentioned above
      #     target_branch: output
      #     build_dir: dist
      #     commit_message: Update snake
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # cron-schedule:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Every time
  #       run: echo "This step will always run"
  
